from __future__ import annotations

def nextprime(n: int, ith: int = ...) -> int: ...
def prime(nth: int) -> int: ...
def primerange(a: int, b: int) -> list[int]: ...
def randprime(a: int, b: int) -> int: ...
